// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.21.12
// source: proto/todofy/database.proto

package todofy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DatabaseType int32

const (
	DatabaseType_DATABASE_TYPE_UNSPECIFIED DatabaseType = 0
	// SQLite database
	DatabaseType_DATABASE_TYPE_SQLITE DatabaseType = 1
)

// Enum value maps for DatabaseType.
var (
	DatabaseType_name = map[int32]string{
		0: "DATABASE_TYPE_UNSPECIFIED",
		1: "DATABASE_TYPE_SQLITE",
	}
	DatabaseType_value = map[string]int32{
		"DATABASE_TYPE_UNSPECIFIED": 0,
		"DATABASE_TYPE_SQLITE":      1,
	}
)

func (x DatabaseType) Enum() *DatabaseType {
	p := new(DatabaseType)
	*p = x
	return p
}

func (x DatabaseType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DatabaseType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_todofy_database_proto_enumTypes[0].Descriptor()
}

func (DatabaseType) Type() protoreflect.EnumType {
	return &file_proto_todofy_database_proto_enumTypes[0]
}

func (x DatabaseType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DatabaseType.Descriptor instead.
func (DatabaseType) EnumDescriptor() ([]byte, []int) {
	return file_proto_todofy_database_proto_rawDescGZIP(), []int{0}
}

type DataBaseSchema struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// the model family
	ModelFamily ModelFamily `protobuf:"varint,1,opt,name=model_family,json=modelFamily,proto3,enum=todofy.ModelFamily" json:"model_family,omitempty"`
	// the model to use for the request.
	Model Model `protobuf:"varint,2,opt,name=model,proto3,enum=todofy.Model" json:"model,omitempty"`
	// The prompt to summarize.
	Prompt string `protobuf:"bytes,3,opt,name=prompt,proto3" json:"prompt,omitempty"`
	// The maximum number of tokens to generate.
	MaxTokens int32 `protobuf:"varint,4,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	// The text to summarize.
	Text string `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
	// The summary of the text.
	Summary string `protobuf:"bytes,6,opt,name=summary,proto3" json:"summary,omitempty"`
	// the timestamp of the entry created.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// the timestamp of the entry updated.
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// a unique hash id for the entry, should be generated from prompt + text.
	HashId string `protobuf:"bytes,9,opt,name=hash_id,json=hashId,proto3" json:"hash_id,omitempty"`
}

func (x *DataBaseSchema) Reset() {
	*x = DataBaseSchema{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_todofy_database_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataBaseSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataBaseSchema) ProtoMessage() {}

func (x *DataBaseSchema) ProtoReflect() protoreflect.Message {
	mi := &file_proto_todofy_database_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataBaseSchema.ProtoReflect.Descriptor instead.
func (*DataBaseSchema) Descriptor() ([]byte, []int) {
	return file_proto_todofy_database_proto_rawDescGZIP(), []int{0}
}

func (x *DataBaseSchema) GetModelFamily() ModelFamily {
	if x != nil {
		return x.ModelFamily
	}
	return ModelFamily_MODEL_FAMILY_UNSPECIFIED
}

func (x *DataBaseSchema) GetModel() Model {
	if x != nil {
		return x.Model
	}
	return Model_MODEL_UNSPECIFIED
}

func (x *DataBaseSchema) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *DataBaseSchema) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *DataBaseSchema) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *DataBaseSchema) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *DataBaseSchema) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *DataBaseSchema) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *DataBaseSchema) GetHashId() string {
	if x != nil {
		return x.HashId
	}
	return ""
}

type WriteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The type of database to use.
	Type DatabaseType `protobuf:"varint,1,opt,name=type,proto3,enum=todofy.DatabaseType" json:"type,omitempty"`
	// The schema of the database.
	Schema *DataBaseSchema `protobuf:"bytes,2,opt,name=schema,proto3" json:"schema,omitempty"`
}

func (x *WriteRequest) Reset() {
	*x = WriteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_todofy_database_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRequest) ProtoMessage() {}

func (x *WriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_todofy_database_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRequest.ProtoReflect.Descriptor instead.
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return file_proto_todofy_database_proto_rawDescGZIP(), []int{1}
}

func (x *WriteRequest) GetType() DatabaseType {
	if x != nil {
		return x.Type
	}
	return DatabaseType_DATABASE_TYPE_UNSPECIFIED
}

func (x *WriteRequest) GetSchema() *DataBaseSchema {
	if x != nil {
		return x.Schema
	}
	return nil
}

type WriteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WriteResponse) Reset() {
	*x = WriteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_todofy_database_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResponse) ProtoMessage() {}

func (x *WriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_todofy_database_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteResponse.ProtoReflect.Descriptor instead.
func (*WriteResponse) Descriptor() ([]byte, []int) {
	return file_proto_todofy_database_proto_rawDescGZIP(), []int{2}
}

type QueryRecentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The type of database to use.
	Type DatabaseType `protobuf:"varint,1,opt,name=type,proto3,enum=todofy.DatabaseType" json:"type,omitempty"`
	// how much time ago to query.
	TimeAgoInSeconds int64 `protobuf:"varint,2,opt,name=time_ago_in_seconds,json=timeAgoInSeconds,proto3" json:"time_ago_in_seconds,omitempty"`
}

func (x *QueryRecentRequest) Reset() {
	*x = QueryRecentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_todofy_database_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryRecentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRecentRequest) ProtoMessage() {}

func (x *QueryRecentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_todofy_database_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRecentRequest.ProtoReflect.Descriptor instead.
func (*QueryRecentRequest) Descriptor() ([]byte, []int) {
	return file_proto_todofy_database_proto_rawDescGZIP(), []int{3}
}

func (x *QueryRecentRequest) GetType() DatabaseType {
	if x != nil {
		return x.Type
	}
	return DatabaseType_DATABASE_TYPE_UNSPECIFIED
}

func (x *QueryRecentRequest) GetTimeAgoInSeconds() int64 {
	if x != nil {
		return x.TimeAgoInSeconds
	}
	return 0
}

type QueryRecentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Recent entries in the database.
	Entries []*DataBaseSchema `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
}

func (x *QueryRecentResponse) Reset() {
	*x = QueryRecentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_todofy_database_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryRecentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRecentResponse) ProtoMessage() {}

func (x *QueryRecentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_todofy_database_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRecentResponse.ProtoReflect.Descriptor instead.
func (*QueryRecentResponse) Descriptor() ([]byte, []int) {
	return file_proto_todofy_database_proto_rawDescGZIP(), []int{4}
}

func (x *QueryRecentResponse) GetEntries() []*DataBaseSchema {
	if x != nil {
		return x.Entries
	}
	return nil
}

type CreateIfNotExistRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The type of database to use.
	Type DatabaseType `protobuf:"varint,1,opt,name=type,proto3,enum=todofy.DatabaseType" json:"type,omitempty"`
	// The path to the database.
	Path string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *CreateIfNotExistRequest) Reset() {
	*x = CreateIfNotExistRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_todofy_database_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateIfNotExistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIfNotExistRequest) ProtoMessage() {}

func (x *CreateIfNotExistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_todofy_database_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIfNotExistRequest.ProtoReflect.Descriptor instead.
func (*CreateIfNotExistRequest) Descriptor() ([]byte, []int) {
	return file_proto_todofy_database_proto_rawDescGZIP(), []int{5}
}

func (x *CreateIfNotExistRequest) GetType() DatabaseType {
	if x != nil {
		return x.Type
	}
	return DatabaseType_DATABASE_TYPE_UNSPECIFIED
}

func (x *CreateIfNotExistRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type CreateIfNotExistResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateIfNotExistResponse) Reset() {
	*x = CreateIfNotExistResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_todofy_database_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateIfNotExistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIfNotExistResponse) ProtoMessage() {}

func (x *CreateIfNotExistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_todofy_database_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIfNotExistResponse.ProtoReflect.Descriptor instead.
func (*CreateIfNotExistResponse) Descriptor() ([]byte, []int) {
	return file_proto_todofy_database_proto_rawDescGZIP(), []int{6}
}

type CheckExistRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The type of database to use.
	Type DatabaseType `protobuf:"varint,1,opt,name=type,proto3,enum=todofy.DatabaseType" json:"type,omitempty"`
	// The hash id to check.
	HashId string `protobuf:"bytes,2,opt,name=hash_id,json=hashId,proto3" json:"hash_id,omitempty"`
}

func (x *CheckExistRequest) Reset() {
	*x = CheckExistRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_todofy_database_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckExistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckExistRequest) ProtoMessage() {}

func (x *CheckExistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_todofy_database_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckExistRequest.ProtoReflect.Descriptor instead.
func (*CheckExistRequest) Descriptor() ([]byte, []int) {
	return file_proto_todofy_database_proto_rawDescGZIP(), []int{7}
}

func (x *CheckExistRequest) GetType() DatabaseType {
	if x != nil {
		return x.Type
	}
	return DatabaseType_DATABASE_TYPE_UNSPECIFIED
}

func (x *CheckExistRequest) GetHashId() string {
	if x != nil {
		return x.HashId
	}
	return ""
}

type CheckExistResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The entry if exists.
	Entry *DataBaseSchema `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
}

func (x *CheckExistResponse) Reset() {
	*x = CheckExistResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_todofy_database_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckExistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckExistResponse) ProtoMessage() {}

func (x *CheckExistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_todofy_database_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckExistResponse.ProtoReflect.Descriptor instead.
func (*CheckExistResponse) Descriptor() ([]byte, []int) {
	return file_proto_todofy_database_proto_rawDescGZIP(), []int{8}
}

func (x *CheckExistResponse) GetEntry() *DataBaseSchema {
	if x != nil {
		return x.Entry
	}
	return nil
}

var File_proto_todofy_database_proto protoreflect.FileDescriptor

var file_proto_todofy_database_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x6f, 0x64, 0x6f, 0x66, 0x79, 0x2f, 0x64,
	0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x74,
	0x6f, 0x64, 0x6f, 0x66, 0x79, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x27, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x6f,
	0x64, 0x6f, 0x66, 0x79, 0x2f, 0x6c, 0x61, 0x72, 0x67, 0x65, 0x5f, 0x6c, 0x61, 0x6e, 0x67, 0x75,
	0x61, 0x67, 0x65, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xe1, 0x02, 0x0a, 0x0e, 0x44, 0x61, 0x74, 0x61, 0x42, 0x61, 0x73, 0x65, 0x53, 0x63, 0x68, 0x65,
	0x6d, 0x61, 0x12, 0x36, 0x0a, 0x0c, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x5f, 0x66, 0x61, 0x6d, 0x69,
	0x6c, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x66,
	0x79, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x52, 0x0b, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x12, 0x23, 0x0a, 0x05, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x74, 0x6f, 0x64, 0x6f,
	0x66, 0x79, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x12,
	0x16, 0x0a, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x61, 0x78, 0x5f, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6d, 0x61, 0x78,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75,
	0x6d, 0x6d, 0x61, 0x72, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x6d,
	0x6d, 0x61, 0x72, 0x79, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f,
	0x61, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12,
	0x39, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x68, 0x61,
	0x73, 0x68, 0x5f, 0x69, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x68, 0x61, 0x73,
	0x68, 0x49, 0x64, 0x22, 0x68, 0x0a, 0x0c, 0x57, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x14, 0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x66, 0x79, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x62,
	0x61, 0x73, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x2e, 0x0a,
	0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x74, 0x6f, 0x64, 0x6f, 0x66, 0x79, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x42, 0x61, 0x73, 0x65, 0x53,
	0x63, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x22, 0x0f, 0x0a,
	0x0d, 0x57, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x6d,
	0x0a, 0x12, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x63, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x14, 0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x66, 0x79, 0x2e, 0x44, 0x61, 0x74, 0x61,
	0x62, 0x61, 0x73, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x2d,
	0x0a, 0x13, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x61, 0x67, 0x6f, 0x5f, 0x69, 0x6e, 0x5f, 0x73, 0x65,
	0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x10, 0x74, 0x69, 0x6d,
	0x65, 0x41, 0x67, 0x6f, 0x49, 0x6e, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x22, 0x47, 0x0a,
	0x13, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x63, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x66, 0x79, 0x2e, 0x44,
	0x61, 0x74, 0x61, 0x42, 0x61, 0x73, 0x65, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x07, 0x65,
	0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x22, 0x57, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x49, 0x66, 0x4e, 0x6f, 0x74, 0x45, 0x78, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x28, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x14, 0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x66, 0x79, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22,
	0x1a, 0x0a, 0x18, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x66, 0x4e, 0x6f, 0x74, 0x45, 0x78,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x56, 0x0a, 0x11, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x45, 0x78, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x28, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14,
	0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x66, 0x79, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x68, 0x61,
	0x73, 0x68, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x68, 0x61, 0x73,
	0x68, 0x49, 0x64, 0x22, 0x42, 0x0a, 0x12, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x45, 0x78, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x05, 0x65, 0x6e, 0x74,
	0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x66,
	0x79, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x42, 0x61, 0x73, 0x65, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61,
	0x52, 0x05, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x2a, 0x47, 0x0a, 0x0c, 0x44, 0x61, 0x74, 0x61, 0x62,
	0x61, 0x73, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x19, 0x44, 0x41, 0x54, 0x41, 0x42,
	0x41, 0x53, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49,
	0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x18, 0x0a, 0x14, 0x44, 0x41, 0x54, 0x41, 0x42, 0x41,
	0x53, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x53, 0x51, 0x4c, 0x49, 0x54, 0x45, 0x10, 0x01,
	0x32, 0xab, 0x02, 0x0a, 0x0f, 0x44, 0x61, 0x74, 0x61, 0x42, 0x61, 0x73, 0x65, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x55, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x66,
	0x4e, 0x6f, 0x74, 0x45, 0x78, 0x69, 0x73, 0x74, 0x12, 0x1f, 0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x66,
	0x79, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x66, 0x4e, 0x6f, 0x74, 0x45, 0x78, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x74, 0x6f, 0x64, 0x6f,
	0x66, 0x79, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x66, 0x4e, 0x6f, 0x74, 0x45, 0x78,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x05, 0x57,
	0x72, 0x69, 0x74, 0x65, 0x12, 0x14, 0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x66, 0x79, 0x2e, 0x57, 0x72,
	0x69, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x74, 0x6f, 0x64,
	0x6f, 0x66, 0x79, 0x2e, 0x57, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x46, 0x0a, 0x0b, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x63, 0x65, 0x6e, 0x74,
	0x12, 0x1a, 0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x66, 0x79, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52,
	0x65, 0x63, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x74,
	0x6f, 0x64, 0x6f, 0x66, 0x79, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x63, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43, 0x0a, 0x0a, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x45, 0x78, 0x69, 0x73, 0x74, 0x12, 0x19, 0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x66, 0x79,
	0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x45, 0x78, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x66, 0x79, 0x2e, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x45, 0x78, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x24,
	0x5a, 0x22, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x7a, 0x69, 0x79,
	0x69, 0x78, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x67, 0x6f, 0x2f, 0x74, 0x6f,
	0x64, 0x6f, 0x66, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_todofy_database_proto_rawDescOnce sync.Once
	file_proto_todofy_database_proto_rawDescData = file_proto_todofy_database_proto_rawDesc
)

func file_proto_todofy_database_proto_rawDescGZIP() []byte {
	file_proto_todofy_database_proto_rawDescOnce.Do(func() {
		file_proto_todofy_database_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_todofy_database_proto_rawDescData)
	})
	return file_proto_todofy_database_proto_rawDescData
}

var file_proto_todofy_database_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_todofy_database_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_todofy_database_proto_goTypes = []interface{}{
	(DatabaseType)(0),                // 0: todofy.DatabaseType
	(*DataBaseSchema)(nil),           // 1: todofy.DataBaseSchema
	(*WriteRequest)(nil),             // 2: todofy.WriteRequest
	(*WriteResponse)(nil),            // 3: todofy.WriteResponse
	(*QueryRecentRequest)(nil),       // 4: todofy.QueryRecentRequest
	(*QueryRecentResponse)(nil),      // 5: todofy.QueryRecentResponse
	(*CreateIfNotExistRequest)(nil),  // 6: todofy.CreateIfNotExistRequest
	(*CreateIfNotExistResponse)(nil), // 7: todofy.CreateIfNotExistResponse
	(*CheckExistRequest)(nil),        // 8: todofy.CheckExistRequest
	(*CheckExistResponse)(nil),       // 9: todofy.CheckExistResponse
	(ModelFamily)(0),                 // 10: todofy.ModelFamily
	(Model)(0),                       // 11: todofy.Model
	(*timestamppb.Timestamp)(nil),    // 12: google.protobuf.Timestamp
}
var file_proto_todofy_database_proto_depIdxs = []int32{
	10, // 0: todofy.DataBaseSchema.model_family:type_name -> todofy.ModelFamily
	11, // 1: todofy.DataBaseSchema.model:type_name -> todofy.Model
	12, // 2: todofy.DataBaseSchema.created_at:type_name -> google.protobuf.Timestamp
	12, // 3: todofy.DataBaseSchema.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 4: todofy.WriteRequest.type:type_name -> todofy.DatabaseType
	1,  // 5: todofy.WriteRequest.schema:type_name -> todofy.DataBaseSchema
	0,  // 6: todofy.QueryRecentRequest.type:type_name -> todofy.DatabaseType
	1,  // 7: todofy.QueryRecentResponse.entries:type_name -> todofy.DataBaseSchema
	0,  // 8: todofy.CreateIfNotExistRequest.type:type_name -> todofy.DatabaseType
	0,  // 9: todofy.CheckExistRequest.type:type_name -> todofy.DatabaseType
	1,  // 10: todofy.CheckExistResponse.entry:type_name -> todofy.DataBaseSchema
	6,  // 11: todofy.DataBaseService.CreateIfNotExist:input_type -> todofy.CreateIfNotExistRequest
	2,  // 12: todofy.DataBaseService.Write:input_type -> todofy.WriteRequest
	4,  // 13: todofy.DataBaseService.QueryRecent:input_type -> todofy.QueryRecentRequest
	8,  // 14: todofy.DataBaseService.CheckExist:input_type -> todofy.CheckExistRequest
	7,  // 15: todofy.DataBaseService.CreateIfNotExist:output_type -> todofy.CreateIfNotExistResponse
	3,  // 16: todofy.DataBaseService.Write:output_type -> todofy.WriteResponse
	5,  // 17: todofy.DataBaseService.QueryRecent:output_type -> todofy.QueryRecentResponse
	9,  // 18: todofy.DataBaseService.CheckExist:output_type -> todofy.CheckExistResponse
	15, // [15:19] is the sub-list for method output_type
	11, // [11:15] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_todofy_database_proto_init() }
func file_proto_todofy_database_proto_init() {
	if File_proto_todofy_database_proto != nil {
		return
	}
	file_proto_todofy_large_language_model_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_todofy_database_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataBaseSchema); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_todofy_database_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_todofy_database_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_todofy_database_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryRecentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_todofy_database_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryRecentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_todofy_database_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateIfNotExistRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_todofy_database_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateIfNotExistResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_todofy_database_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckExistRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_todofy_database_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckExistResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_todofy_database_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_todofy_database_proto_goTypes,
		DependencyIndexes: file_proto_todofy_database_proto_depIdxs,
		EnumInfos:         file_proto_todofy_database_proto_enumTypes,
		MessageInfos:      file_proto_todofy_database_proto_msgTypes,
	}.Build()
	File_proto_todofy_database_proto = out.File
	file_proto_todofy_database_proto_rawDesc = nil
	file_proto_todofy_database_proto_goTypes = nil
	file_proto_todofy_database_proto_depIdxs = nil
}
