// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: proto/todofy/dependency.proto

package todofy

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	DependencyService_ReconcileGraph_FullMethodName           = "/todofy.DependencyService/ReconcileGraph"
	DependencyService_AnalyzeGraph_FullMethodName             = "/todofy.DependencyService/AnalyzeGraph"
	DependencyService_BootstrapMissingTaskKeys_FullMethodName = "/todofy.DependencyService/BootstrapMissingTaskKeys"
	DependencyService_GetTaskStatus_FullMethodName            = "/todofy.DependencyService/GetTaskStatus"
	DependencyService_ListDependencyIssues_FullMethodName     = "/todofy.DependencyService/ListDependencyIssues"
	DependencyService_MarkGraphDirty_FullMethodName           = "/todofy.DependencyService/MarkGraphDirty"
)

// DependencyServiceClient is the client API for DependencyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DependencyServiceClient interface {
	// Reconcile graph state and persist side effects.
	ReconcileGraph(ctx context.Context, in *ReconcileDependencyGraphRequest, opts ...grpc.CallOption) (*ReconcileDependencyGraphResponse, error)
	// Analyze graph state without writes.
	AnalyzeGraph(ctx context.Context, in *AnalyzeDependencyGraphRequest, opts ...grpc.CallOption) (*AnalyzeDependencyGraphResponse, error)
	// Generate and persist missing stable task keys.
	BootstrapMissingTaskKeys(ctx context.Context, in *BootstrapMissingTaskKeysRequest, opts ...grpc.CallOption) (*BootstrapMissingTaskKeysResponse, error)
	// Get dependency status for one task.
	GetTaskStatus(ctx context.Context, in *GetTaskDependencyStatusRequest, opts ...grpc.CallOption) (*GetTaskDependencyStatusResponse, error)
	// List graph issues.
	ListDependencyIssues(ctx context.Context, in *ListDependencyIssuesRequest, opts ...grpc.CallOption) (*ListDependencyIssuesResponse, error)
	// Mark graph state dirty from external hints such as webhooks.
	MarkGraphDirty(ctx context.Context, in *MarkDependencyGraphDirtyRequest, opts ...grpc.CallOption) (*MarkDependencyGraphDirtyResponse, error)
}

type dependencyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDependencyServiceClient(cc grpc.ClientConnInterface) DependencyServiceClient {
	return &dependencyServiceClient{cc}
}

func (c *dependencyServiceClient) ReconcileGraph(ctx context.Context, in *ReconcileDependencyGraphRequest, opts ...grpc.CallOption) (*ReconcileDependencyGraphResponse, error) {
	out := new(ReconcileDependencyGraphResponse)
	err := c.cc.Invoke(ctx, DependencyService_ReconcileGraph_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dependencyServiceClient) AnalyzeGraph(ctx context.Context, in *AnalyzeDependencyGraphRequest, opts ...grpc.CallOption) (*AnalyzeDependencyGraphResponse, error) {
	out := new(AnalyzeDependencyGraphResponse)
	err := c.cc.Invoke(ctx, DependencyService_AnalyzeGraph_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dependencyServiceClient) BootstrapMissingTaskKeys(ctx context.Context, in *BootstrapMissingTaskKeysRequest, opts ...grpc.CallOption) (*BootstrapMissingTaskKeysResponse, error) {
	out := new(BootstrapMissingTaskKeysResponse)
	err := c.cc.Invoke(ctx, DependencyService_BootstrapMissingTaskKeys_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dependencyServiceClient) GetTaskStatus(ctx context.Context, in *GetTaskDependencyStatusRequest, opts ...grpc.CallOption) (*GetTaskDependencyStatusResponse, error) {
	out := new(GetTaskDependencyStatusResponse)
	err := c.cc.Invoke(ctx, DependencyService_GetTaskStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dependencyServiceClient) ListDependencyIssues(ctx context.Context, in *ListDependencyIssuesRequest, opts ...grpc.CallOption) (*ListDependencyIssuesResponse, error) {
	out := new(ListDependencyIssuesResponse)
	err := c.cc.Invoke(ctx, DependencyService_ListDependencyIssues_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dependencyServiceClient) MarkGraphDirty(ctx context.Context, in *MarkDependencyGraphDirtyRequest, opts ...grpc.CallOption) (*MarkDependencyGraphDirtyResponse, error) {
	out := new(MarkDependencyGraphDirtyResponse)
	err := c.cc.Invoke(ctx, DependencyService_MarkGraphDirty_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DependencyServiceServer is the server API for DependencyService service.
// All implementations must embed UnimplementedDependencyServiceServer
// for forward compatibility
type DependencyServiceServer interface {
	// Reconcile graph state and persist side effects.
	ReconcileGraph(context.Context, *ReconcileDependencyGraphRequest) (*ReconcileDependencyGraphResponse, error)
	// Analyze graph state without writes.
	AnalyzeGraph(context.Context, *AnalyzeDependencyGraphRequest) (*AnalyzeDependencyGraphResponse, error)
	// Generate and persist missing stable task keys.
	BootstrapMissingTaskKeys(context.Context, *BootstrapMissingTaskKeysRequest) (*BootstrapMissingTaskKeysResponse, error)
	// Get dependency status for one task.
	GetTaskStatus(context.Context, *GetTaskDependencyStatusRequest) (*GetTaskDependencyStatusResponse, error)
	// List graph issues.
	ListDependencyIssues(context.Context, *ListDependencyIssuesRequest) (*ListDependencyIssuesResponse, error)
	// Mark graph state dirty from external hints such as webhooks.
	MarkGraphDirty(context.Context, *MarkDependencyGraphDirtyRequest) (*MarkDependencyGraphDirtyResponse, error)
	mustEmbedUnimplementedDependencyServiceServer()
}

// UnimplementedDependencyServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDependencyServiceServer struct {
}

func (UnimplementedDependencyServiceServer) ReconcileGraph(context.Context, *ReconcileDependencyGraphRequest) (*ReconcileDependencyGraphResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReconcileGraph not implemented")
}
func (UnimplementedDependencyServiceServer) AnalyzeGraph(context.Context, *AnalyzeDependencyGraphRequest) (*AnalyzeDependencyGraphResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AnalyzeGraph not implemented")
}
func (UnimplementedDependencyServiceServer) BootstrapMissingTaskKeys(context.Context, *BootstrapMissingTaskKeysRequest) (*BootstrapMissingTaskKeysResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BootstrapMissingTaskKeys not implemented")
}
func (UnimplementedDependencyServiceServer) GetTaskStatus(context.Context, *GetTaskDependencyStatusRequest) (*GetTaskDependencyStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTaskStatus not implemented")
}
func (UnimplementedDependencyServiceServer) ListDependencyIssues(context.Context, *ListDependencyIssuesRequest) (*ListDependencyIssuesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDependencyIssues not implemented")
}
func (UnimplementedDependencyServiceServer) MarkGraphDirty(context.Context, *MarkDependencyGraphDirtyRequest) (*MarkDependencyGraphDirtyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarkGraphDirty not implemented")
}
func (UnimplementedDependencyServiceServer) mustEmbedUnimplementedDependencyServiceServer() {}

// UnsafeDependencyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DependencyServiceServer will
// result in compilation errors.
type UnsafeDependencyServiceServer interface {
	mustEmbedUnimplementedDependencyServiceServer()
}

func RegisterDependencyServiceServer(s grpc.ServiceRegistrar, srv DependencyServiceServer) {
	s.RegisterService(&DependencyService_ServiceDesc, srv)
}

func _DependencyService_ReconcileGraph_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReconcileDependencyGraphRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DependencyServiceServer).ReconcileGraph(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DependencyService_ReconcileGraph_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DependencyServiceServer).ReconcileGraph(ctx, req.(*ReconcileDependencyGraphRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DependencyService_AnalyzeGraph_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeDependencyGraphRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DependencyServiceServer).AnalyzeGraph(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DependencyService_AnalyzeGraph_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DependencyServiceServer).AnalyzeGraph(ctx, req.(*AnalyzeDependencyGraphRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DependencyService_BootstrapMissingTaskKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BootstrapMissingTaskKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DependencyServiceServer).BootstrapMissingTaskKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DependencyService_BootstrapMissingTaskKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DependencyServiceServer).BootstrapMissingTaskKeys(ctx, req.(*BootstrapMissingTaskKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DependencyService_GetTaskStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskDependencyStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DependencyServiceServer).GetTaskStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DependencyService_GetTaskStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DependencyServiceServer).GetTaskStatus(ctx, req.(*GetTaskDependencyStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DependencyService_ListDependencyIssues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDependencyIssuesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DependencyServiceServer).ListDependencyIssues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DependencyService_ListDependencyIssues_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DependencyServiceServer).ListDependencyIssues(ctx, req.(*ListDependencyIssuesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DependencyService_MarkGraphDirty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkDependencyGraphDirtyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DependencyServiceServer).MarkGraphDirty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DependencyService_MarkGraphDirty_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DependencyServiceServer).MarkGraphDirty(ctx, req.(*MarkDependencyGraphDirtyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DependencyService_ServiceDesc is the grpc.ServiceDesc for DependencyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DependencyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "todofy.DependencyService",
	HandlerType: (*DependencyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReconcileGraph",
			Handler:    _DependencyService_ReconcileGraph_Handler,
		},
		{
			MethodName: "AnalyzeGraph",
			Handler:    _DependencyService_AnalyzeGraph_Handler,
		},
		{
			MethodName: "BootstrapMissingTaskKeys",
			Handler:    _DependencyService_BootstrapMissingTaskKeys_Handler,
		},
		{
			MethodName: "GetTaskStatus",
			Handler:    _DependencyService_GetTaskStatus_Handler,
		},
		{
			MethodName: "ListDependencyIssues",
			Handler:    _DependencyService_ListDependencyIssues_Handler,
		},
		{
			MethodName: "MarkGraphDirty",
			Handler:    _DependencyService_MarkGraphDirty_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/todofy/dependency.proto",
}
