// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.21.12
// source: proto/todofy/large_language_model.proto

package todofy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ModelFamily int32

const (
	// The model family is unspecified.
	ModelFamily_MODEL_FAMILY_UNSPECIFIED ModelFamily = 0
	// The model family is Gemini.
	ModelFamily_MODEL_FAMILY_GEMINI ModelFamily = 1
)

// Enum value maps for ModelFamily.
var (
	ModelFamily_name = map[int32]string{
		0: "MODEL_FAMILY_UNSPECIFIED",
		1: "MODEL_FAMILY_GEMINI",
	}
	ModelFamily_value = map[string]int32{
		"MODEL_FAMILY_UNSPECIFIED": 0,
		"MODEL_FAMILY_GEMINI":      1,
	}
)

func (x ModelFamily) Enum() *ModelFamily {
	p := new(ModelFamily)
	*p = x
	return p
}

func (x ModelFamily) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ModelFamily) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_todofy_large_language_model_proto_enumTypes[0].Descriptor()
}

func (ModelFamily) Type() protoreflect.EnumType {
	return &file_proto_todofy_large_language_model_proto_enumTypes[0]
}

func (x ModelFamily) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ModelFamily.Descriptor instead.
func (ModelFamily) EnumDescriptor() ([]byte, []int) {
	return file_proto_todofy_large_language_model_proto_rawDescGZIP(), []int{0}
}

type Model int32

const (
	Model_MODEL_UNSPECIFIED Model = 0
	// gemini-2.0-pro-exp-02-05
	//
	// Deprecated: Marked as deprecated in proto/todofy/large_language_model.proto.
	Model_MODEL_GEMINI_2_0_PRO_EXP_02_05 Model = 1
	// gemini-1.5-pro
	//
	// Deprecated: Marked as deprecated in proto/todofy/large_language_model.proto.
	Model_MODEL_GEMINI_1_5_PRO Model = 2
	// gemini-2.0-flash
	Model_MODEL_GEMINI_2_0_FLASH Model = 3
	// gemini-1.5-flash
	//
	// Deprecated: Marked as deprecated in proto/todofy/large_language_model.proto.
	Model_MODEL_GEMINI_1_5_FLASH Model = 4
	// gemini-2.5-pro-preview-03-25
	Model_MODEL_GEMINI_2_5_PRO_PREVIEW_03_25 Model = 5
	// gemini-2.5-flash-preview-04-17
	Model_MODEL_GEMINI_2_5_FLASH_PREVIEW_04_17 Model = 6
	// gemini-2.0-flash-lite
	Model_MODEL_GEMINI_2_0_FLASH_LITE Model = 7
)

// Enum value maps for Model.
var (
	Model_name = map[int32]string{
		0: "MODEL_UNSPECIFIED",
		1: "MODEL_GEMINI_2_0_PRO_EXP_02_05",
		2: "MODEL_GEMINI_1_5_PRO",
		3: "MODEL_GEMINI_2_0_FLASH",
		4: "MODEL_GEMINI_1_5_FLASH",
		5: "MODEL_GEMINI_2_5_PRO_PREVIEW_03_25",
		6: "MODEL_GEMINI_2_5_FLASH_PREVIEW_04_17",
		7: "MODEL_GEMINI_2_0_FLASH_LITE",
	}
	Model_value = map[string]int32{
		"MODEL_UNSPECIFIED":                    0,
		"MODEL_GEMINI_2_0_PRO_EXP_02_05":       1,
		"MODEL_GEMINI_1_5_PRO":                 2,
		"MODEL_GEMINI_2_0_FLASH":               3,
		"MODEL_GEMINI_1_5_FLASH":               4,
		"MODEL_GEMINI_2_5_PRO_PREVIEW_03_25":   5,
		"MODEL_GEMINI_2_5_FLASH_PREVIEW_04_17": 6,
		"MODEL_GEMINI_2_0_FLASH_LITE":          7,
	}
)

func (x Model) Enum() *Model {
	p := new(Model)
	*p = x
	return p
}

func (x Model) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Model) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_todofy_large_language_model_proto_enumTypes[1].Descriptor()
}

func (Model) Type() protoreflect.EnumType {
	return &file_proto_todofy_large_language_model_proto_enumTypes[1]
}

func (x Model) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Model.Descriptor instead.
func (Model) EnumDescriptor() ([]byte, []int) {
	return file_proto_todofy_large_language_model_proto_rawDescGZIP(), []int{1}
}

type LLMSummaryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// model family
	ModelFamily ModelFamily `protobuf:"varint,1,opt,name=model_family,json=modelFamily,proto3,enum=todofy.ModelFamily" json:"model_family,omitempty"`
	// The model to use for the request.
	Model Model `protobuf:"varint,2,opt,name=model,proto3,enum=todofy.Model" json:"model,omitempty"`
	// The prompt to summarize.
	Prompt string `protobuf:"bytes,3,opt,name=prompt,proto3" json:"prompt,omitempty"`
	// The maximum number of tokens to generate.
	MaxTokens int32 `protobuf:"varint,4,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	// The text to summarize.
	Text string `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *LLMSummaryRequest) Reset() {
	*x = LLMSummaryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_todofy_large_language_model_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LLMSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMSummaryRequest) ProtoMessage() {}

func (x *LLMSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_todofy_large_language_model_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMSummaryRequest.ProtoReflect.Descriptor instead.
func (*LLMSummaryRequest) Descriptor() ([]byte, []int) {
	return file_proto_todofy_large_language_model_proto_rawDescGZIP(), []int{0}
}

func (x *LLMSummaryRequest) GetModelFamily() ModelFamily {
	if x != nil {
		return x.ModelFamily
	}
	return ModelFamily_MODEL_FAMILY_UNSPECIFIED
}

func (x *LLMSummaryRequest) GetModel() Model {
	if x != nil {
		return x.Model
	}
	return Model_MODEL_UNSPECIFIED
}

func (x *LLMSummaryRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *LLMSummaryRequest) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *LLMSummaryRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type LLMSummaryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The summary of the text.
	Summary string `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	// The model used for the request.
	Model Model `protobuf:"varint,2,opt,name=model,proto3,enum=todofy.Model" json:"model,omitempty"`
}

func (x *LLMSummaryResponse) Reset() {
	*x = LLMSummaryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_todofy_large_language_model_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LLMSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMSummaryResponse) ProtoMessage() {}

func (x *LLMSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_todofy_large_language_model_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMSummaryResponse.ProtoReflect.Descriptor instead.
func (*LLMSummaryResponse) Descriptor() ([]byte, []int) {
	return file_proto_todofy_large_language_model_proto_rawDescGZIP(), []int{1}
}

func (x *LLMSummaryResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *LLMSummaryResponse) GetModel() Model {
	if x != nil {
		return x.Model
	}
	return Model_MODEL_UNSPECIFIED
}

var File_proto_todofy_large_language_model_proto protoreflect.FileDescriptor

var file_proto_todofy_large_language_model_proto_rawDesc = []byte{
	0x0a, 0x27, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x6f, 0x64, 0x6f, 0x66, 0x79, 0x2f, 0x6c,
	0x61, 0x72, 0x67, 0x65, 0x5f, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x5f, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x74, 0x6f, 0x64, 0x6f, 0x66,
	0x79, 0x22, 0xbb, 0x01, 0x0a, 0x11, 0x4c, 0x4c, 0x4d, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x36, 0x0a, 0x0c, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x5f, 0x66, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e,
	0x74, 0x6f, 0x64, 0x6f, 0x66, 0x79, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x46, 0x61, 0x6d, 0x69,
	0x6c, 0x79, 0x52, 0x0b, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x12,
	0x23, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d,
	0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x66, 0x79, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x05, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x12, 0x1d, 0x0a, 0x0a,
	0x6d, 0x61, 0x78, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x09, 0x6d, 0x61, 0x78, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x65, 0x78, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22,
	0x53, 0x0a, 0x12, 0x4c, 0x4c, 0x4d, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12,
	0x23, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d,
	0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x66, 0x79, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x05, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x2a, 0x44, 0x0a, 0x0b, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x46, 0x61, 0x6d,
	0x69, 0x6c, 0x79, 0x12, 0x1c, 0x0a, 0x18, 0x4d, 0x4f, 0x44, 0x45, 0x4c, 0x5f, 0x46, 0x41, 0x4d,
	0x49, 0x4c, 0x59, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10,
	0x00, 0x12, 0x17, 0x0a, 0x13, 0x4d, 0x4f, 0x44, 0x45, 0x4c, 0x5f, 0x46, 0x41, 0x4d, 0x49, 0x4c,
	0x59, 0x5f, 0x47, 0x45, 0x4d, 0x49, 0x4e, 0x49, 0x10, 0x01, 0x2a, 0x93, 0x02, 0x0a, 0x05, 0x4d,
	0x6f, 0x64, 0x65, 0x6c, 0x12, 0x15, 0x0a, 0x11, 0x4d, 0x4f, 0x44, 0x45, 0x4c, 0x5f, 0x55, 0x4e,
	0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x26, 0x0a, 0x1e, 0x4d,
	0x4f, 0x44, 0x45, 0x4c, 0x5f, 0x47, 0x45, 0x4d, 0x49, 0x4e, 0x49, 0x5f, 0x32, 0x5f, 0x30, 0x5f,
	0x50, 0x52, 0x4f, 0x5f, 0x45, 0x58, 0x50, 0x5f, 0x30, 0x32, 0x5f, 0x30, 0x35, 0x10, 0x01, 0x1a,
	0x02, 0x08, 0x01, 0x12, 0x1c, 0x0a, 0x14, 0x4d, 0x4f, 0x44, 0x45, 0x4c, 0x5f, 0x47, 0x45, 0x4d,
	0x49, 0x4e, 0x49, 0x5f, 0x31, 0x5f, 0x35, 0x5f, 0x50, 0x52, 0x4f, 0x10, 0x02, 0x1a, 0x02, 0x08,
	0x01, 0x12, 0x1a, 0x0a, 0x16, 0x4d, 0x4f, 0x44, 0x45, 0x4c, 0x5f, 0x47, 0x45, 0x4d, 0x49, 0x4e,
	0x49, 0x5f, 0x32, 0x5f, 0x30, 0x5f, 0x46, 0x4c, 0x41, 0x53, 0x48, 0x10, 0x03, 0x12, 0x1e, 0x0a,
	0x16, 0x4d, 0x4f, 0x44, 0x45, 0x4c, 0x5f, 0x47, 0x45, 0x4d, 0x49, 0x4e, 0x49, 0x5f, 0x31, 0x5f,
	0x35, 0x5f, 0x46, 0x4c, 0x41, 0x53, 0x48, 0x10, 0x04, 0x1a, 0x02, 0x08, 0x01, 0x12, 0x26, 0x0a,
	0x22, 0x4d, 0x4f, 0x44, 0x45, 0x4c, 0x5f, 0x47, 0x45, 0x4d, 0x49, 0x4e, 0x49, 0x5f, 0x32, 0x5f,
	0x35, 0x5f, 0x50, 0x52, 0x4f, 0x5f, 0x50, 0x52, 0x45, 0x56, 0x49, 0x45, 0x57, 0x5f, 0x30, 0x33,
	0x5f, 0x32, 0x35, 0x10, 0x05, 0x12, 0x28, 0x0a, 0x24, 0x4d, 0x4f, 0x44, 0x45, 0x4c, 0x5f, 0x47,
	0x45, 0x4d, 0x49, 0x4e, 0x49, 0x5f, 0x32, 0x5f, 0x35, 0x5f, 0x46, 0x4c, 0x41, 0x53, 0x48, 0x5f,
	0x50, 0x52, 0x45, 0x56, 0x49, 0x45, 0x57, 0x5f, 0x30, 0x34, 0x5f, 0x31, 0x37, 0x10, 0x06, 0x12,
	0x1f, 0x0a, 0x1b, 0x4d, 0x4f, 0x44, 0x45, 0x4c, 0x5f, 0x47, 0x45, 0x4d, 0x49, 0x4e, 0x49, 0x5f,
	0x32, 0x5f, 0x30, 0x5f, 0x46, 0x4c, 0x41, 0x53, 0x48, 0x5f, 0x4c, 0x49, 0x54, 0x45, 0x10, 0x07,
	0x32, 0x57, 0x0a, 0x11, 0x4c, 0x4c, 0x4d, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x42, 0x0a, 0x09, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x69,
	0x7a, 0x65, 0x12, 0x19, 0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x66, 0x79, 0x2e, 0x4c, 0x4c, 0x4d, 0x53,
	0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e,
	0x74, 0x6f, 0x64, 0x6f, 0x66, 0x79, 0x2e, 0x4c, 0x4c, 0x4d, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x24, 0x5a, 0x22, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x7a, 0x69, 0x79, 0x69, 0x78, 0x69, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x67, 0x6f, 0x2f, 0x74, 0x6f, 0x64, 0x6f, 0x66, 0x79, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_todofy_large_language_model_proto_rawDescOnce sync.Once
	file_proto_todofy_large_language_model_proto_rawDescData = file_proto_todofy_large_language_model_proto_rawDesc
)

func file_proto_todofy_large_language_model_proto_rawDescGZIP() []byte {
	file_proto_todofy_large_language_model_proto_rawDescOnce.Do(func() {
		file_proto_todofy_large_language_model_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_todofy_large_language_model_proto_rawDescData)
	})
	return file_proto_todofy_large_language_model_proto_rawDescData
}

var file_proto_todofy_large_language_model_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_todofy_large_language_model_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_todofy_large_language_model_proto_goTypes = []interface{}{
	(ModelFamily)(0),           // 0: todofy.ModelFamily
	(Model)(0),                 // 1: todofy.Model
	(*LLMSummaryRequest)(nil),  // 2: todofy.LLMSummaryRequest
	(*LLMSummaryResponse)(nil), // 3: todofy.LLMSummaryResponse
}
var file_proto_todofy_large_language_model_proto_depIdxs = []int32{
	0, // 0: todofy.LLMSummaryRequest.model_family:type_name -> todofy.ModelFamily
	1, // 1: todofy.LLMSummaryRequest.model:type_name -> todofy.Model
	1, // 2: todofy.LLMSummaryResponse.model:type_name -> todofy.Model
	2, // 3: todofy.LLMSummaryService.Summarize:input_type -> todofy.LLMSummaryRequest
	3, // 4: todofy.LLMSummaryService.Summarize:output_type -> todofy.LLMSummaryResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_todofy_large_language_model_proto_init() }
func file_proto_todofy_large_language_model_proto_init() {
	if File_proto_todofy_large_language_model_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_todofy_large_language_model_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LLMSummaryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_todofy_large_language_model_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LLMSummaryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_todofy_large_language_model_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_todofy_large_language_model_proto_goTypes,
		DependencyIndexes: file_proto_todofy_large_language_model_proto_depIdxs,
		EnumInfos:         file_proto_todofy_large_language_model_proto_enumTypes,
		MessageInfos:      file_proto_todofy_large_language_model_proto_msgTypes,
	}.Build()
	File_proto_todofy_large_language_model_proto = out.File
	file_proto_todofy_large_language_model_proto_rawDesc = nil
	file_proto_todofy_large_language_model_proto_goTypes = nil
	file_proto_todofy_large_language_model_proto_depIdxs = nil
}
