// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.21.12
// source: proto/todofy/todoist.proto

package todofy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Parsed dependency metadata extracted from a task title.
type ParsedDependencyMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Stable human-friendly task key.
	TaskKey string `protobuf:"bytes,1,opt,name=task_key,json=taskKey,proto3" json:"task_key,omitempty"`
	// Dependency keys referenced by the task.
	DependencyKeys []string `protobuf:"bytes,2,rep,name=dependency_keys,json=dependencyKeys,proto3" json:"dependency_keys,omitempty"`
	// Whether metadata parsing was successful.
	Valid bool `protobuf:"varint,3,opt,name=valid,proto3" json:"valid,omitempty"`
	// Parsing error details when valid is false.
	ParseError string `protobuf:"bytes,4,opt,name=parse_error,json=parseError,proto3" json:"parse_error,omitempty"`
}

func (x *ParsedDependencyMetadata) Reset() {
	*x = ParsedDependencyMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_todofy_todoist_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParsedDependencyMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParsedDependencyMetadata) ProtoMessage() {}

func (x *ParsedDependencyMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_todofy_todoist_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParsedDependencyMetadata.ProtoReflect.Descriptor instead.
func (*ParsedDependencyMetadata) Descriptor() ([]byte, []int) {
	return file_proto_todofy_todoist_proto_rawDescGZIP(), []int{0}
}

func (x *ParsedDependencyMetadata) GetTaskKey() string {
	if x != nil {
		return x.TaskKey
	}
	return ""
}

func (x *ParsedDependencyMetadata) GetDependencyKeys() []string {
	if x != nil {
		return x.DependencyKeys
	}
	return nil
}

func (x *ParsedDependencyMetadata) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ParsedDependencyMetadata) GetParseError() string {
	if x != nil {
		return x.ParseError
	}
	return ""
}

// Normalized Todoist task view used by dependency flows.
type NormalizedTodoistTask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Raw Todoist task id.
	TodoistTaskId string `protobuf:"bytes,1,opt,name=todoist_task_id,json=todoistTaskId,proto3" json:"todoist_task_id,omitempty"`
	// User-visible task content.
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	// Completion state from Todoist.
	Completed bool `protobuf:"varint,3,opt,name=completed,proto3" json:"completed,omitempty"`
	// Current labels on the task.
	Labels []string `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty"`
	// Parsed dependency metadata from task content.
	Metadata *ParsedDependencyMetadata `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (x *NormalizedTodoistTask) Reset() {
	*x = NormalizedTodoistTask{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_todofy_todoist_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NormalizedTodoistTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NormalizedTodoistTask) ProtoMessage() {}

func (x *NormalizedTodoistTask) ProtoReflect() protoreflect.Message {
	mi := &file_proto_todofy_todoist_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NormalizedTodoistTask.ProtoReflect.Descriptor instead.
func (*NormalizedTodoistTask) Descriptor() ([]byte, []int) {
	return file_proto_todofy_todoist_proto_rawDescGZIP(), []int{1}
}

func (x *NormalizedTodoistTask) GetTodoistTaskId() string {
	if x != nil {
		return x.TodoistTaskId
	}
	return ""
}

func (x *NormalizedTodoistTask) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *NormalizedTodoistTask) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

func (x *NormalizedTodoistTask) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *NormalizedTodoistTask) GetMetadata() *ParsedDependencyMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type GetTodoistTaskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TodoistTaskId string `protobuf:"bytes,1,opt,name=todoist_task_id,json=todoistTaskId,proto3" json:"todoist_task_id,omitempty"`
}

func (x *GetTodoistTaskRequest) Reset() {
	*x = GetTodoistTaskRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_todofy_todoist_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTodoistTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTodoistTaskRequest) ProtoMessage() {}

func (x *GetTodoistTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_todofy_todoist_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTodoistTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTodoistTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_todofy_todoist_proto_rawDescGZIP(), []int{2}
}

func (x *GetTodoistTaskRequest) GetTodoistTaskId() string {
	if x != nil {
		return x.TodoistTaskId
	}
	return ""
}

type GetTodoistTaskResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Task *NormalizedTodoistTask `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
}

func (x *GetTodoistTaskResponse) Reset() {
	*x = GetTodoistTaskResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_todofy_todoist_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTodoistTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTodoistTaskResponse) ProtoMessage() {}

func (x *GetTodoistTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_todofy_todoist_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTodoistTaskResponse.ProtoReflect.Descriptor instead.
func (*GetTodoistTaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_todofy_todoist_proto_rawDescGZIP(), []int{3}
}

func (x *GetTodoistTaskResponse) GetTask() *NormalizedTodoistTask {
	if x != nil {
		return x.Task
	}
	return nil
}

type ListActiveTodoistTasksRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListActiveTodoistTasksRequest) Reset() {
	*x = ListActiveTodoistTasksRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_todofy_todoist_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListActiveTodoistTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActiveTodoistTasksRequest) ProtoMessage() {}

func (x *ListActiveTodoistTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_todofy_todoist_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActiveTodoistTasksRequest.ProtoReflect.Descriptor instead.
func (*ListActiveTodoistTasksRequest) Descriptor() ([]byte, []int) {
	return file_proto_todofy_todoist_proto_rawDescGZIP(), []int{4}
}

type ListActiveTodoistTasksResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tasks []*NormalizedTodoistTask `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
}

func (x *ListActiveTodoistTasksResponse) Reset() {
	*x = ListActiveTodoistTasksResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_todofy_todoist_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListActiveTodoistTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActiveTodoistTasksResponse) ProtoMessage() {}

func (x *ListActiveTodoistTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_todofy_todoist_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActiveTodoistTasksResponse.ProtoReflect.Descriptor instead.
func (*ListActiveTodoistTasksResponse) Descriptor() ([]byte, []int) {
	return file_proto_todofy_todoist_proto_rawDescGZIP(), []int{5}
}

func (x *ListActiveTodoistTasksResponse) GetTasks() []*NormalizedTodoistTask {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type UpdateTodoistTaskLabelsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TodoistTaskId string   `protobuf:"bytes,1,opt,name=todoist_task_id,json=todoistTaskId,proto3" json:"todoist_task_id,omitempty"`
	AddLabels     []string `protobuf:"bytes,2,rep,name=add_labels,json=addLabels,proto3" json:"add_labels,omitempty"`
	RemoveLabels  []string `protobuf:"bytes,3,rep,name=remove_labels,json=removeLabels,proto3" json:"remove_labels,omitempty"`
}

func (x *UpdateTodoistTaskLabelsRequest) Reset() {
	*x = UpdateTodoistTaskLabelsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_todofy_todoist_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTodoistTaskLabelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTodoistTaskLabelsRequest) ProtoMessage() {}

func (x *UpdateTodoistTaskLabelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_todofy_todoist_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTodoistTaskLabelsRequest.ProtoReflect.Descriptor instead.
func (*UpdateTodoistTaskLabelsRequest) Descriptor() ([]byte, []int) {
	return file_proto_todofy_todoist_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateTodoistTaskLabelsRequest) GetTodoistTaskId() string {
	if x != nil {
		return x.TodoistTaskId
	}
	return ""
}

func (x *UpdateTodoistTaskLabelsRequest) GetAddLabels() []string {
	if x != nil {
		return x.AddLabels
	}
	return nil
}

func (x *UpdateTodoistTaskLabelsRequest) GetRemoveLabels() []string {
	if x != nil {
		return x.RemoveLabels
	}
	return nil
}

type UpdateTodoistTaskLabelsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Task *NormalizedTodoistTask `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
}

func (x *UpdateTodoistTaskLabelsResponse) Reset() {
	*x = UpdateTodoistTaskLabelsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_todofy_todoist_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTodoistTaskLabelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTodoistTaskLabelsResponse) ProtoMessage() {}

func (x *UpdateTodoistTaskLabelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_todofy_todoist_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTodoistTaskLabelsResponse.ProtoReflect.Descriptor instead.
func (*UpdateTodoistTaskLabelsResponse) Descriptor() ([]byte, []int) {
	return file_proto_todofy_todoist_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateTodoistTaskLabelsResponse) GetTask() *NormalizedTodoistTask {
	if x != nil {
		return x.Task
	}
	return nil
}

type TodoistWebhookHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *TodoistWebhookHeader) Reset() {
	*x = TodoistWebhookHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_todofy_todoist_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TodoistWebhookHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TodoistWebhookHeader) ProtoMessage() {}

func (x *TodoistWebhookHeader) ProtoReflect() protoreflect.Message {
	mi := &file_proto_todofy_todoist_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TodoistWebhookHeader.ProtoReflect.Descriptor instead.
func (*TodoistWebhookHeader) Descriptor() ([]byte, []int) {
	return file_proto_todofy_todoist_proto_rawDescGZIP(), []int{8}
}

func (x *TodoistWebhookHeader) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *TodoistWebhookHeader) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type VerifyTodoistWebhookRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Raw request body bytes used for signature verification.
	RawBody []byte `protobuf:"bytes,1,opt,name=raw_body,json=rawBody,proto3" json:"raw_body,omitempty"`
	// Full request headers when available.
	Headers []*TodoistWebhookHeader `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty"`
	// Optional direct signature input if already extracted by caller.
	Signature string `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *VerifyTodoistWebhookRequest) Reset() {
	*x = VerifyTodoistWebhookRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_todofy_todoist_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyTodoistWebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTodoistWebhookRequest) ProtoMessage() {}

func (x *VerifyTodoistWebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_todofy_todoist_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTodoistWebhookRequest.ProtoReflect.Descriptor instead.
func (*VerifyTodoistWebhookRequest) Descriptor() ([]byte, []int) {
	return file_proto_todofy_todoist_proto_rawDescGZIP(), []int{9}
}

func (x *VerifyTodoistWebhookRequest) GetRawBody() []byte {
	if x != nil {
		return x.RawBody
	}
	return nil
}

func (x *VerifyTodoistWebhookRequest) GetHeaders() []*TodoistWebhookHeader {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *VerifyTodoistWebhookRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type VerifyTodoistWebhookResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Valid bool `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	// Short verification reason, such as "ok" or "missing_signature".
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	// Optional implementation-specific details for logs/debugging.
	Details string `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
}

func (x *VerifyTodoistWebhookResponse) Reset() {
	*x = VerifyTodoistWebhookResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_todofy_todoist_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyTodoistWebhookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTodoistWebhookResponse) ProtoMessage() {}

func (x *VerifyTodoistWebhookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_todofy_todoist_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTodoistWebhookResponse.ProtoReflect.Descriptor instead.
func (*VerifyTodoistWebhookResponse) Descriptor() ([]byte, []int) {
	return file_proto_todofy_todoist_proto_rawDescGZIP(), []int{10}
}

func (x *VerifyTodoistWebhookResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *VerifyTodoistWebhookResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *VerifyTodoistWebhookResponse) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

type EnsureTodoistLabelsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Labels []string `protobuf:"bytes,1,rep,name=labels,proto3" json:"labels,omitempty"`
}

func (x *EnsureTodoistLabelsRequest) Reset() {
	*x = EnsureTodoistLabelsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_todofy_todoist_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnsureTodoistLabelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureTodoistLabelsRequest) ProtoMessage() {}

func (x *EnsureTodoistLabelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_todofy_todoist_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureTodoistLabelsRequest.ProtoReflect.Descriptor instead.
func (*EnsureTodoistLabelsRequest) Descriptor() ([]byte, []int) {
	return file_proto_todofy_todoist_proto_rawDescGZIP(), []int{11}
}

func (x *EnsureTodoistLabelsRequest) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type EnsureTodoistLabelFailure struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Label  string `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *EnsureTodoistLabelFailure) Reset() {
	*x = EnsureTodoistLabelFailure{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_todofy_todoist_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnsureTodoistLabelFailure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureTodoistLabelFailure) ProtoMessage() {}

func (x *EnsureTodoistLabelFailure) ProtoReflect() protoreflect.Message {
	mi := &file_proto_todofy_todoist_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureTodoistLabelFailure.ProtoReflect.Descriptor instead.
func (*EnsureTodoistLabelFailure) Descriptor() ([]byte, []int) {
	return file_proto_todofy_todoist_proto_rawDescGZIP(), []int{12}
}

func (x *EnsureTodoistLabelFailure) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *EnsureTodoistLabelFailure) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type EnsureTodoistLabelsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExistingLabels []string                     `protobuf:"bytes,1,rep,name=existing_labels,json=existingLabels,proto3" json:"existing_labels,omitempty"`
	CreatedLabels  []string                     `protobuf:"bytes,2,rep,name=created_labels,json=createdLabels,proto3" json:"created_labels,omitempty"`
	Failures       []*EnsureTodoistLabelFailure `protobuf:"bytes,3,rep,name=failures,proto3" json:"failures,omitempty"`
}

func (x *EnsureTodoistLabelsResponse) Reset() {
	*x = EnsureTodoistLabelsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_todofy_todoist_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnsureTodoistLabelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureTodoistLabelsResponse) ProtoMessage() {}

func (x *EnsureTodoistLabelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_todofy_todoist_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureTodoistLabelsResponse.ProtoReflect.Descriptor instead.
func (*EnsureTodoistLabelsResponse) Descriptor() ([]byte, []int) {
	return file_proto_todofy_todoist_proto_rawDescGZIP(), []int{13}
}

func (x *EnsureTodoistLabelsResponse) GetExistingLabels() []string {
	if x != nil {
		return x.ExistingLabels
	}
	return nil
}

func (x *EnsureTodoistLabelsResponse) GetCreatedLabels() []string {
	if x != nil {
		return x.CreatedLabels
	}
	return nil
}

func (x *EnsureTodoistLabelsResponse) GetFailures() []*EnsureTodoistLabelFailure {
	if x != nil {
		return x.Failures
	}
	return nil
}

var File_proto_todofy_todoist_proto protoreflect.FileDescriptor

var file_proto_todofy_todoist_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x6f, 0x64, 0x6f, 0x66, 0x79, 0x2f, 0x74,
	0x6f, 0x64, 0x6f, 0x69, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x74, 0x6f,
	0x64, 0x6f, 0x66, 0x79, 0x22, 0x95, 0x01, 0x0a, 0x18, 0x50, 0x61, 0x72, 0x73, 0x65, 0x64, 0x44,
	0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x79, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x4b, 0x65, 0x79, 0x12, 0x27, 0x0a, 0x0f,
	0x64, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x79, 0x5f, 0x6b, 0x65, 0x79, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0e, 0x64, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63,
	0x79, 0x4b, 0x65, 0x79, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x70,
	0x61, 0x72, 0x73, 0x65, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x70, 0x61, 0x72, 0x73, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x22, 0xcd, 0x01, 0x0a,
	0x15, 0x4e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x54, 0x6f, 0x64, 0x6f, 0x69,
	0x73, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x26, 0x0a, 0x0f, 0x74, 0x6f, 0x64, 0x6f, 0x69, 0x73,
	0x74, 0x5f, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x74, 0x6f, 0x64, 0x6f, 0x69, 0x73, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x70,
	0x6c, 0x65, 0x74, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x63, 0x6f, 0x6d,
	0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x12, 0x3c,
	0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x20, 0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x66, 0x79, 0x2e, 0x50, 0x61, 0x72, 0x73, 0x65, 0x64,
	0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x79, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x22, 0x3f, 0x0a, 0x15,
	0x47, 0x65, 0x74, 0x54, 0x6f, 0x64, 0x6f, 0x69, 0x73, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x0f, 0x74, 0x6f, 0x64, 0x6f, 0x69, 0x73, 0x74,
	0x5f, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x74, 0x6f, 0x64, 0x6f, 0x69, 0x73, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x22, 0x4b, 0x0a,
	0x16, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x64, 0x6f, 0x69, 0x73, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x66, 0x79, 0x2e, 0x4e,
	0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x54, 0x6f, 0x64, 0x6f, 0x69, 0x73, 0x74,
	0x54, 0x61, 0x73, 0x6b, 0x52, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x22, 0x1f, 0x0a, 0x1d, 0x4c, 0x69,
	0x73, 0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x54, 0x6f, 0x64, 0x6f, 0x69, 0x73, 0x74, 0x54,
	0x61, 0x73, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x55, 0x0a, 0x1e, 0x4c,
	0x69, 0x73, 0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x54, 0x6f, 0x64, 0x6f, 0x69, 0x73, 0x74,
	0x54, 0x61, 0x73, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a,
	0x05, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x74,
	0x6f, 0x64, 0x6f, 0x66, 0x79, 0x2e, 0x4e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64,
	0x54, 0x6f, 0x64, 0x6f, 0x69, 0x73, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x05, 0x74, 0x61, 0x73,
	0x6b, 0x73, 0x22, 0x8c, 0x01, 0x0a, 0x1e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x64,
	0x6f, 0x69, 0x73, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x0f, 0x74, 0x6f, 0x64, 0x6f, 0x69, 0x73, 0x74,
	0x5f, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x74, 0x6f, 0x64, 0x6f, 0x69, 0x73, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12, 0x1d, 0x0a,
	0x0a, 0x61, 0x64, 0x64, 0x5f, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x09, 0x61, 0x64, 0x64, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x12, 0x23, 0x0a, 0x0d,
	0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x5f, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4c, 0x61, 0x62, 0x65, 0x6c,
	0x73, 0x22, 0x54, 0x0a, 0x1f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x64, 0x6f, 0x69,
	0x73, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x66, 0x79, 0x2e, 0x4e, 0x6f, 0x72, 0x6d,
	0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x54, 0x6f, 0x64, 0x6f, 0x69, 0x73, 0x74, 0x54, 0x61, 0x73,
	0x6b, 0x52, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x22, 0x3e, 0x0a, 0x14, 0x54, 0x6f, 0x64, 0x6f, 0x69,
	0x73, 0x74, 0x57, 0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x8e, 0x01, 0x0a, 0x1b, 0x56, 0x65, 0x72, 0x69,
	0x66, 0x79, 0x54, 0x6f, 0x64, 0x6f, 0x69, 0x73, 0x74, 0x57, 0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x61, 0x77, 0x5f, 0x62,
	0x6f, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x72, 0x61, 0x77, 0x42, 0x6f,
	0x64, 0x79, 0x12, 0x36, 0x0a, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x66, 0x79, 0x2e, 0x54, 0x6f, 0x64,
	0x6f, 0x69, 0x73, 0x74, 0x57, 0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x48, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x52, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69,
	0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73,
	0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0x66, 0x0a, 0x1c, 0x56, 0x65, 0x72, 0x69,
	0x66, 0x79, 0x54, 0x6f, 0x64, 0x6f, 0x69, 0x73, 0x74, 0x57, 0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73,
	0x22, 0x34, 0x0a, 0x1a, 0x45, 0x6e, 0x73, 0x75, 0x72, 0x65, 0x54, 0x6f, 0x64, 0x6f, 0x69, 0x73,
	0x74, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06,
	0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x22, 0x49, 0x0a, 0x19, 0x45, 0x6e, 0x73, 0x75, 0x72, 0x65,
	0x54, 0x6f, 0x64, 0x6f, 0x69, 0x73, 0x74, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x46, 0x61, 0x69, 0x6c,
	0x75, 0x72, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61,
	0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x22, 0xac, 0x01, 0x0a, 0x1b, 0x45, 0x6e, 0x73, 0x75, 0x72, 0x65, 0x54, 0x6f, 0x64, 0x6f,
	0x69, 0x73, 0x74, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x27, 0x0a, 0x0f, 0x65, 0x78, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x6c, 0x61,
	0x62, 0x65, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0e, 0x65, 0x78, 0x69, 0x73,
	0x74, 0x69, 0x6e, 0x67, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x0d, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x4c, 0x61, 0x62, 0x65, 0x6c,
	0x73, 0x12, 0x3d, 0x0a, 0x08, 0x66, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x66, 0x79, 0x2e, 0x45, 0x6e, 0x73,
	0x75, 0x72, 0x65, 0x54, 0x6f, 0x64, 0x6f, 0x69, 0x73, 0x74, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x46,
	0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x52, 0x08, 0x66, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x73,
	0x32, 0xd6, 0x03, 0x0a, 0x0e, 0x54, 0x6f, 0x64, 0x6f, 0x69, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x48, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x1d,
	0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x66, 0x79, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x64, 0x6f, 0x69,
	0x73, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e,
	0x74, 0x6f, 0x64, 0x6f, 0x66, 0x79, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x64, 0x6f, 0x69, 0x73,
	0x74, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x60, 0x0a,
	0x0f, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x73,
	0x12, 0x25, 0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x66, 0x79, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x63,
	0x74, 0x69, 0x76, 0x65, 0x54, 0x6f, 0x64, 0x6f, 0x69, 0x73, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x66, 0x79,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x54, 0x6f, 0x64, 0x6f, 0x69,
	0x73, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x63, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x4c, 0x61, 0x62,
	0x65, 0x6c, 0x73, 0x12, 0x26, 0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x66, 0x79, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x54, 0x6f, 0x64, 0x6f, 0x69, 0x73, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x4c, 0x61,
	0x62, 0x65, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x74, 0x6f,
	0x64, 0x6f, 0x66, 0x79, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x64, 0x6f, 0x69,
	0x73, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5a, 0x0a, 0x0d, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x57, 0x65,
	0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x12, 0x23, 0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x66, 0x79, 0x2e, 0x56,
	0x65, 0x72, 0x69, 0x66, 0x79, 0x54, 0x6f, 0x64, 0x6f, 0x69, 0x73, 0x74, 0x57, 0x65, 0x62, 0x68,
	0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x74, 0x6f, 0x64,
	0x6f, 0x66, 0x79, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x54, 0x6f, 0x64, 0x6f, 0x69, 0x73,
	0x74, 0x57, 0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x57, 0x0a, 0x0c, 0x45, 0x6e, 0x73, 0x75, 0x72, 0x65, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73,
	0x12, 0x22, 0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x66, 0x79, 0x2e, 0x45, 0x6e, 0x73, 0x75, 0x72, 0x65,
	0x54, 0x6f, 0x64, 0x6f, 0x69, 0x73, 0x74, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x66, 0x79, 0x2e, 0x45, 0x6e,
	0x73, 0x75, 0x72, 0x65, 0x54, 0x6f, 0x64, 0x6f, 0x69, 0x73, 0x74, 0x4c, 0x61, 0x62, 0x65, 0x6c,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x24, 0x5a, 0x22, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x7a, 0x69, 0x79, 0x69, 0x78, 0x69, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x67, 0x6f, 0x2f, 0x74, 0x6f, 0x64, 0x6f, 0x66, 0x79, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_todofy_todoist_proto_rawDescOnce sync.Once
	file_proto_todofy_todoist_proto_rawDescData = file_proto_todofy_todoist_proto_rawDesc
)

func file_proto_todofy_todoist_proto_rawDescGZIP() []byte {
	file_proto_todofy_todoist_proto_rawDescOnce.Do(func() {
		file_proto_todofy_todoist_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_todofy_todoist_proto_rawDescData)
	})
	return file_proto_todofy_todoist_proto_rawDescData
}

var file_proto_todofy_todoist_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_todofy_todoist_proto_goTypes = []interface{}{
	(*ParsedDependencyMetadata)(nil),        // 0: todofy.ParsedDependencyMetadata
	(*NormalizedTodoistTask)(nil),           // 1: todofy.NormalizedTodoistTask
	(*GetTodoistTaskRequest)(nil),           // 2: todofy.GetTodoistTaskRequest
	(*GetTodoistTaskResponse)(nil),          // 3: todofy.GetTodoistTaskResponse
	(*ListActiveTodoistTasksRequest)(nil),   // 4: todofy.ListActiveTodoistTasksRequest
	(*ListActiveTodoistTasksResponse)(nil),  // 5: todofy.ListActiveTodoistTasksResponse
	(*UpdateTodoistTaskLabelsRequest)(nil),  // 6: todofy.UpdateTodoistTaskLabelsRequest
	(*UpdateTodoistTaskLabelsResponse)(nil), // 7: todofy.UpdateTodoistTaskLabelsResponse
	(*TodoistWebhookHeader)(nil),            // 8: todofy.TodoistWebhookHeader
	(*VerifyTodoistWebhookRequest)(nil),     // 9: todofy.VerifyTodoistWebhookRequest
	(*VerifyTodoistWebhookResponse)(nil),    // 10: todofy.VerifyTodoistWebhookResponse
	(*EnsureTodoistLabelsRequest)(nil),      // 11: todofy.EnsureTodoistLabelsRequest
	(*EnsureTodoistLabelFailure)(nil),       // 12: todofy.EnsureTodoistLabelFailure
	(*EnsureTodoistLabelsResponse)(nil),     // 13: todofy.EnsureTodoistLabelsResponse
}
var file_proto_todofy_todoist_proto_depIdxs = []int32{
	0,  // 0: todofy.NormalizedTodoistTask.metadata:type_name -> todofy.ParsedDependencyMetadata
	1,  // 1: todofy.GetTodoistTaskResponse.task:type_name -> todofy.NormalizedTodoistTask
	1,  // 2: todofy.ListActiveTodoistTasksResponse.tasks:type_name -> todofy.NormalizedTodoistTask
	1,  // 3: todofy.UpdateTodoistTaskLabelsResponse.task:type_name -> todofy.NormalizedTodoistTask
	8,  // 4: todofy.VerifyTodoistWebhookRequest.headers:type_name -> todofy.TodoistWebhookHeader
	12, // 5: todofy.EnsureTodoistLabelsResponse.failures:type_name -> todofy.EnsureTodoistLabelFailure
	2,  // 6: todofy.TodoistService.GetTask:input_type -> todofy.GetTodoistTaskRequest
	4,  // 7: todofy.TodoistService.ListActiveTasks:input_type -> todofy.ListActiveTodoistTasksRequest
	6,  // 8: todofy.TodoistService.UpdateTaskLabels:input_type -> todofy.UpdateTodoistTaskLabelsRequest
	9,  // 9: todofy.TodoistService.VerifyWebhook:input_type -> todofy.VerifyTodoistWebhookRequest
	11, // 10: todofy.TodoistService.EnsureLabels:input_type -> todofy.EnsureTodoistLabelsRequest
	3,  // 11: todofy.TodoistService.GetTask:output_type -> todofy.GetTodoistTaskResponse
	5,  // 12: todofy.TodoistService.ListActiveTasks:output_type -> todofy.ListActiveTodoistTasksResponse
	7,  // 13: todofy.TodoistService.UpdateTaskLabels:output_type -> todofy.UpdateTodoistTaskLabelsResponse
	10, // 14: todofy.TodoistService.VerifyWebhook:output_type -> todofy.VerifyTodoistWebhookResponse
	13, // 15: todofy.TodoistService.EnsureLabels:output_type -> todofy.EnsureTodoistLabelsResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_todofy_todoist_proto_init() }
func file_proto_todofy_todoist_proto_init() {
	if File_proto_todofy_todoist_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_todofy_todoist_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParsedDependencyMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_todofy_todoist_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NormalizedTodoistTask); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_todofy_todoist_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTodoistTaskRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_todofy_todoist_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTodoistTaskResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_todofy_todoist_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListActiveTodoistTasksRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_todofy_todoist_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListActiveTodoistTasksResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_todofy_todoist_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateTodoistTaskLabelsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_todofy_todoist_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateTodoistTaskLabelsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_todofy_todoist_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TodoistWebhookHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_todofy_todoist_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyTodoistWebhookRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_todofy_todoist_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyTodoistWebhookResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_todofy_todoist_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnsureTodoistLabelsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_todofy_todoist_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnsureTodoistLabelFailure); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_todofy_todoist_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnsureTodoistLabelsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_todofy_todoist_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_todofy_todoist_proto_goTypes,
		DependencyIndexes: file_proto_todofy_todoist_proto_depIdxs,
		MessageInfos:      file_proto_todofy_todoist_proto_msgTypes,
	}.Build()
	File_proto_todofy_todoist_proto = out.File
	file_proto_todofy_todoist_proto_rawDesc = nil
	file_proto_todofy_todoist_proto_goTypes = nil
	file_proto_todofy_todoist_proto_depIdxs = nil
}
