// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: proto/todofy/todoist.proto

package todofy

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	TodoistService_GetTask_FullMethodName          = "/todofy.TodoistService/GetTask"
	TodoistService_ListActiveTasks_FullMethodName  = "/todofy.TodoistService/ListActiveTasks"
	TodoistService_UpdateTaskLabels_FullMethodName = "/todofy.TodoistService/UpdateTaskLabels"
	TodoistService_VerifyWebhook_FullMethodName    = "/todofy.TodoistService/VerifyWebhook"
	TodoistService_EnsureLabels_FullMethodName     = "/todofy.TodoistService/EnsureLabels"
)

// TodoistServiceClient is the client API for TodoistService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TodoistServiceClient interface {
	// Get one task by Todoist task id.
	GetTask(ctx context.Context, in *GetTodoistTaskRequest, opts ...grpc.CallOption) (*GetTodoistTaskResponse, error)
	// List active (not completed) tasks.
	ListActiveTasks(ctx context.Context, in *ListActiveTodoistTasksRequest, opts ...grpc.CallOption) (*ListActiveTodoistTasksResponse, error)
	// Add/remove labels for a task.
	UpdateTaskLabels(ctx context.Context, in *UpdateTodoistTaskLabelsRequest, opts ...grpc.CallOption) (*UpdateTodoistTaskLabelsResponse, error)
	// Verify webhook authenticity.
	VerifyWebhook(ctx context.Context, in *VerifyTodoistWebhookRequest, opts ...grpc.CallOption) (*VerifyTodoistWebhookResponse, error)
	// Ensure required labels exist in Todoist.
	EnsureLabels(ctx context.Context, in *EnsureTodoistLabelsRequest, opts ...grpc.CallOption) (*EnsureTodoistLabelsResponse, error)
}

type todoistServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTodoistServiceClient(cc grpc.ClientConnInterface) TodoistServiceClient {
	return &todoistServiceClient{cc}
}

func (c *todoistServiceClient) GetTask(ctx context.Context, in *GetTodoistTaskRequest, opts ...grpc.CallOption) (*GetTodoistTaskResponse, error) {
	out := new(GetTodoistTaskResponse)
	err := c.cc.Invoke(ctx, TodoistService_GetTask_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoistServiceClient) ListActiveTasks(ctx context.Context, in *ListActiveTodoistTasksRequest, opts ...grpc.CallOption) (*ListActiveTodoistTasksResponse, error) {
	out := new(ListActiveTodoistTasksResponse)
	err := c.cc.Invoke(ctx, TodoistService_ListActiveTasks_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoistServiceClient) UpdateTaskLabels(ctx context.Context, in *UpdateTodoistTaskLabelsRequest, opts ...grpc.CallOption) (*UpdateTodoistTaskLabelsResponse, error) {
	out := new(UpdateTodoistTaskLabelsResponse)
	err := c.cc.Invoke(ctx, TodoistService_UpdateTaskLabels_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoistServiceClient) VerifyWebhook(ctx context.Context, in *VerifyTodoistWebhookRequest, opts ...grpc.CallOption) (*VerifyTodoistWebhookResponse, error) {
	out := new(VerifyTodoistWebhookResponse)
	err := c.cc.Invoke(ctx, TodoistService_VerifyWebhook_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoistServiceClient) EnsureLabels(ctx context.Context, in *EnsureTodoistLabelsRequest, opts ...grpc.CallOption) (*EnsureTodoistLabelsResponse, error) {
	out := new(EnsureTodoistLabelsResponse)
	err := c.cc.Invoke(ctx, TodoistService_EnsureLabels_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TodoistServiceServer is the server API for TodoistService service.
// All implementations must embed UnimplementedTodoistServiceServer
// for forward compatibility
type TodoistServiceServer interface {
	// Get one task by Todoist task id.
	GetTask(context.Context, *GetTodoistTaskRequest) (*GetTodoistTaskResponse, error)
	// List active (not completed) tasks.
	ListActiveTasks(context.Context, *ListActiveTodoistTasksRequest) (*ListActiveTodoistTasksResponse, error)
	// Add/remove labels for a task.
	UpdateTaskLabels(context.Context, *UpdateTodoistTaskLabelsRequest) (*UpdateTodoistTaskLabelsResponse, error)
	// Verify webhook authenticity.
	VerifyWebhook(context.Context, *VerifyTodoistWebhookRequest) (*VerifyTodoistWebhookResponse, error)
	// Ensure required labels exist in Todoist.
	EnsureLabels(context.Context, *EnsureTodoistLabelsRequest) (*EnsureTodoistLabelsResponse, error)
	mustEmbedUnimplementedTodoistServiceServer()
}

// UnimplementedTodoistServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTodoistServiceServer struct {
}

func (UnimplementedTodoistServiceServer) GetTask(context.Context, *GetTodoistTaskRequest) (*GetTodoistTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTask not implemented")
}
func (UnimplementedTodoistServiceServer) ListActiveTasks(context.Context, *ListActiveTodoistTasksRequest) (*ListActiveTodoistTasksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListActiveTasks not implemented")
}
func (UnimplementedTodoistServiceServer) UpdateTaskLabels(context.Context, *UpdateTodoistTaskLabelsRequest) (*UpdateTodoistTaskLabelsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTaskLabels not implemented")
}
func (UnimplementedTodoistServiceServer) VerifyWebhook(context.Context, *VerifyTodoistWebhookRequest) (*VerifyTodoistWebhookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyWebhook not implemented")
}
func (UnimplementedTodoistServiceServer) EnsureLabels(context.Context, *EnsureTodoistLabelsRequest) (*EnsureTodoistLabelsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnsureLabels not implemented")
}
func (UnimplementedTodoistServiceServer) mustEmbedUnimplementedTodoistServiceServer() {}

// UnsafeTodoistServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TodoistServiceServer will
// result in compilation errors.
type UnsafeTodoistServiceServer interface {
	mustEmbedUnimplementedTodoistServiceServer()
}

func RegisterTodoistServiceServer(s grpc.ServiceRegistrar, srv TodoistServiceServer) {
	s.RegisterService(&TodoistService_ServiceDesc, srv)
}

func _TodoistService_GetTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTodoistTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoistServiceServer).GetTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TodoistService_GetTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoistServiceServer).GetTask(ctx, req.(*GetTodoistTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoistService_ListActiveTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListActiveTodoistTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoistServiceServer).ListActiveTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TodoistService_ListActiveTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoistServiceServer).ListActiveTasks(ctx, req.(*ListActiveTodoistTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoistService_UpdateTaskLabels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTodoistTaskLabelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoistServiceServer).UpdateTaskLabels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TodoistService_UpdateTaskLabels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoistServiceServer).UpdateTaskLabels(ctx, req.(*UpdateTodoistTaskLabelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoistService_VerifyWebhook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyTodoistWebhookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoistServiceServer).VerifyWebhook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TodoistService_VerifyWebhook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoistServiceServer).VerifyWebhook(ctx, req.(*VerifyTodoistWebhookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoistService_EnsureLabels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnsureTodoistLabelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoistServiceServer).EnsureLabels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TodoistService_EnsureLabels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoistServiceServer).EnsureLabels(ctx, req.(*EnsureTodoistLabelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TodoistService_ServiceDesc is the grpc.ServiceDesc for TodoistService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TodoistService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "todofy.TodoistService",
	HandlerType: (*TodoistServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTask",
			Handler:    _TodoistService_GetTask_Handler,
		},
		{
			MethodName: "ListActiveTasks",
			Handler:    _TodoistService_ListActiveTasks_Handler,
		},
		{
			MethodName: "UpdateTaskLabels",
			Handler:    _TodoistService_UpdateTaskLabels_Handler,
		},
		{
			MethodName: "VerifyWebhook",
			Handler:    _TodoistService_VerifyWebhook_Handler,
		},
		{
			MethodName: "EnsureLabels",
			Handler:    _TodoistService_EnsureLabels_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/todofy/todoist.proto",
}
