// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: proto/newsletter/editorial.proto

package newsletterpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	NewsletterService_StartRun_FullMethodName    = "/newsletter.v1.NewsletterService/StartRun"
	NewsletterService_GetRun_FullMethodName      = "/newsletter.v1.NewsletterService/GetRun"
	NewsletterService_GetEdition_FullMethodName  = "/newsletter.v1.NewsletterService/GetEdition"
	NewsletterService_SendEdition_FullMethodName = "/newsletter.v1.NewsletterService/SendEdition"
)

// NewsletterServiceClient is the client API for NewsletterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NewsletterServiceClient interface {
	StartRun(ctx context.Context, in *StartRunRequest, opts ...grpc.CallOption) (*CollectionRun, error)
	GetRun(ctx context.Context, in *GetRunRequest, opts ...grpc.CallOption) (*CollectionRun, error)
	GetEdition(ctx context.Context, in *GetEditionRequest, opts ...grpc.CallOption) (*Edition, error)
	SendEdition(ctx context.Context, in *SendEditionRequest, opts ...grpc.CallOption) (*Edition, error)
}

type newsletterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNewsletterServiceClient(cc grpc.ClientConnInterface) NewsletterServiceClient {
	return &newsletterServiceClient{cc}
}

func (c *newsletterServiceClient) StartRun(ctx context.Context, in *StartRunRequest, opts ...grpc.CallOption) (*CollectionRun, error) {
	out := new(CollectionRun)
	err := c.cc.Invoke(ctx, NewsletterService_StartRun_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *newsletterServiceClient) GetRun(ctx context.Context, in *GetRunRequest, opts ...grpc.CallOption) (*CollectionRun, error) {
	out := new(CollectionRun)
	err := c.cc.Invoke(ctx, NewsletterService_GetRun_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *newsletterServiceClient) GetEdition(ctx context.Context, in *GetEditionRequest, opts ...grpc.CallOption) (*Edition, error) {
	out := new(Edition)
	err := c.cc.Invoke(ctx, NewsletterService_GetEdition_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *newsletterServiceClient) SendEdition(ctx context.Context, in *SendEditionRequest, opts ...grpc.CallOption) (*Edition, error) {
	out := new(Edition)
	err := c.cc.Invoke(ctx, NewsletterService_SendEdition_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NewsletterServiceServer is the server API for NewsletterService service.
// All implementations must embed UnimplementedNewsletterServiceServer
// for forward compatibility
type NewsletterServiceServer interface {
	StartRun(context.Context, *StartRunRequest) (*CollectionRun, error)
	GetRun(context.Context, *GetRunRequest) (*CollectionRun, error)
	GetEdition(context.Context, *GetEditionRequest) (*Edition, error)
	SendEdition(context.Context, *SendEditionRequest) (*Edition, error)
	mustEmbedUnimplementedNewsletterServiceServer()
}

// UnimplementedNewsletterServiceServer must be embedded to have forward compatible implementations.
type UnimplementedNewsletterServiceServer struct {
}

func (UnimplementedNewsletterServiceServer) StartRun(context.Context, *StartRunRequest) (*CollectionRun, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartRun not implemented")
}
func (UnimplementedNewsletterServiceServer) GetRun(context.Context, *GetRunRequest) (*CollectionRun, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRun not implemented")
}
func (UnimplementedNewsletterServiceServer) GetEdition(context.Context, *GetEditionRequest) (*Edition, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEdition not implemented")
}
func (UnimplementedNewsletterServiceServer) SendEdition(context.Context, *SendEditionRequest) (*Edition, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendEdition not implemented")
}
func (UnimplementedNewsletterServiceServer) mustEmbedUnimplementedNewsletterServiceServer() {}

// UnsafeNewsletterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NewsletterServiceServer will
// result in compilation errors.
type UnsafeNewsletterServiceServer interface {
	mustEmbedUnimplementedNewsletterServiceServer()
}

func RegisterNewsletterServiceServer(s grpc.ServiceRegistrar, srv NewsletterServiceServer) {
	s.RegisterService(&NewsletterService_ServiceDesc, srv)
}

func _NewsletterService_StartRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewsletterServiceServer).StartRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NewsletterService_StartRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewsletterServiceServer).StartRun(ctx, req.(*StartRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NewsletterService_GetRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewsletterServiceServer).GetRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NewsletterService_GetRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewsletterServiceServer).GetRun(ctx, req.(*GetRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NewsletterService_GetEdition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEditionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewsletterServiceServer).GetEdition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NewsletterService_GetEdition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewsletterServiceServer).GetEdition(ctx, req.(*GetEditionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NewsletterService_SendEdition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendEditionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewsletterServiceServer).SendEdition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NewsletterService_SendEdition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewsletterServiceServer).SendEdition(ctx, req.(*SendEditionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NewsletterService_ServiceDesc is the grpc.ServiceDesc for NewsletterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NewsletterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "newsletter.v1.NewsletterService",
	HandlerType: (*NewsletterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartRun",
			Handler:    _NewsletterService_StartRun_Handler,
		},
		{
			MethodName: "GetRun",
			Handler:    _NewsletterService_GetRun_Handler,
		},
		{
			MethodName: "GetEdition",
			Handler:    _NewsletterService_GetEdition_Handler,
		},
		{
			MethodName: "SendEdition",
			Handler:    _NewsletterService_SendEdition_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/newsletter/editorial.proto",
}
