name: Generate Go Modules from Proto Files

on:
  push:
    branches: main
    paths:
      - 'proto/**'
      - 'scripts/generate-go-proto.sh'
  pull_request:
    branches: main
    paths:
      - 'proto/**'
      - 'scripts/generate-go-proto.sh'
  workflow_dispatch:  # Allow manual triggering

jobs:
  generate-go-modules:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.0'
      
      - name: Install Protoc
        run: |
          sudo apt-get update && sudo apt-get install -y protobuf-compiler
          protoc --version
      
      - name: Install Go Protobuf Plugins
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2
          export PATH="$PATH:$(go env GOPATH)/bin"
      
      - name: Generate Go Modules
        run: |
          chmod +x ./scripts/generate-go-proto.sh
          export MODULE_PREFIX="github.com/${{ github.repository }}"
          export PATH="$PATH:$(go env GOPATH)/bin"
          ./scripts/generate-go-proto.sh
      
      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add go/
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-generate Go modules from Proto files"
          git push